<?php


namespace common\widgets;


use yii\bootstrap4\NavBar;
use yii\widgets\Menu;

class LandingNav extends NavBar
{

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
    }

    protected function renderItem($item)
    {
        return parent::renderItem($item); // TODO: Change the autogenerated stub
    }

    protected function renderItems($items)
    {
        return parent::renderItems($items); // TODO: Change the autogenerated stub
    }

    protected function normalizeItems($items, &$active)
    {
        return parent::normalizeItems($items, $active); // TODO: Change the autogenerated stub
    }
    protected function isItemActive($item)
    {
        return parent::isItemActive($item); // TODO: Change the autogenerated stub
    }


}